//
//
// seasonDataGather() - using the XML and the HTML generated by generateHTML2.js, it generates a javascript object with all the data entered into the webpage.
//                              This object will be sent to the Controller phone where it will be sent to the database.
//
//
var data = new Object();

function seasonDataGather(seasonXML)
{
    gatherRadioData()

    console.log(data);
    return data;
}

function gatherRadioData(data)
{
    data.test = "true";
    $('div.content').find("input[type=radio]:checked").each(function()
							    {
								var name = $(this).attr("name");
								console.log(data);
								data[name] = $(this).val();
							    });
}
